### ISSUE TITLE
This looks amazing! One question please : )

### ISSUE THREAD

**Issue by vesper8** [iminashi/Rocksmith2014.NET#18]
Hello! I am late to the Rocksmith party (very late) so please excuse the beginner question.

I've been looking into using Rocksmith to learn some Spanish guitar instrumental songs.

I've looked into the process of creating CDLCs and it seems that until very recently doing so required you to use 4 or 5 programs:

UltraStar Creator
Editor on fire
Guitar Pro
Rocksmith Toolkit
Wwise

By the way I'd love to do the whole process on Mac, so happy to see you offer a Mac version!

Is it my understanding that your absolutely awesome program replaces the need to juggle 5 programs and you now only need to use this one toolkit that you've developed?

Is there a tutorial or a video anywhere that makes use of your software?

In my case, I have tabs, and I want to practice them in Rocksmith. There are no lyrics and no other instruments as it happens.

Many many thanks! So nice to see something fresh and actively developed in 2023 for Rocksmith!!

**Comment by iminashi** [comment]
Unfortunately, you still need multiple programs for CDLC creation.

This program mainly replaces the Toolkit, any program you would use to calculate volume values, and some of my own tools (mainly DDC Improver). Wwise is also still needed, but you just need to have it installed.

I don't own a mac, so I haven't been able to test the mac version in a long time, so I'm not sure if it still works 100%.

There is also a new Rocksmith-specific [program that replaces EOF](https://github.com/Lordszynencja/LoG-Charter-RS) in development. (See #rs-charter channel in the CustomsForge discord).

I toyed with the idea of developing an "all-in-one solution" some time ago, but decided not work on such a thing when RS+ was announced.

The [main CDLC creation tutorial](https://customsforge.com/index.php?/topic/35318-cdlc-creation-for-rocksmith-2014-remastered/) uses my program. I don't know if any good video tutorials exist.

**Comment by vesper8** [comment]
Thanks for the reply and all that info! Very helpful!
